AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: reserva-request-lambda

Globals:
  Function:
    Timeout: 600

Resources:
  AccessLogs:
    Type: AWS::Logs::LogGroup

  ReservaRequestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./reserva_request
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - arm64
      Layers:
        - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPython:13
        - !Ref GSpreadLayer
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: reserva_request
          TZ: Asia/Tokyo
      Policies:
      - Statement:
        - Sid: SSMDescribeParametersPolicy
          Effect: Allow
          Action:
          - ssm:DescribeParameters
          Resource: '*'
        - Sid: SSMPutGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameters
          - ssm:GetParameter
          - ssm:PutParameters
          - ssm:PutParameter
          Resource: '*'

  CreateAccessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./reserva_request
      Handler: app.batch_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Layers:
        - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPython:13
        - !Ref GSpreadLayer
      Events:
        CreateAccessFunctionEvent:
          Type: Schedule
          Properties:
            Schedule: cron(30 23 ? * FRI *)
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: create_access
          TZ: Asia/Tokyo
      Policies:
      - Statement:
        - Sid: SSMDescribeParametersPolicy
          Effect: Allow
          Action:
          - ssm:DescribeParameters
          Resource: '*'
        - Sid: SSMPutGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameters
          - ssm:GetParameter
          - ssm:PutParameters
          - ssm:PutParameter
          Resource: '*'

  GSpreadLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer description
      ContentUri: 'gspread_layer/'
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

Outputs:
  MyFunctionUrlEndpoint:
    Description: "My Lambda Function URL Endpoint"
    Value:
      Fn::GetAtt: ReservaRequestFunctionUrl.FunctionUrl