AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: reserva-request-lambda

Globals:
  Function:
    Timeout: 600

Resources:
  AccessLogs:
    Type: AWS::Logs::LogGroup

  ReservaRequestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./reserva_request
      Handler: app.handler
      Runtime: python3.11
      Architectures:
        - arm64
      Layers:
        - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:42
        - !Ref GSpreadLayer
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: reserva_request
          TZ: Asia/Tokyo
      Policies:
        - S3FullAccessPolicy:
            BucketName: '{{resolve:ssm:reserva_bucket_info}}'
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMPutGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            - ssm:PutParameters
            - ssm:PutParameter
            Resource: '*'

  CreateAccessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./reserva_request
      Handler: app.batch_handler
      Runtime: python3.11
      Architectures:
        - arm64
      Layers:
        - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:42
        - !Ref GSpreadLayer
      Events:
        ScheduleV2Event:
          Type: ScheduleV2
          Properties:
            Name: CreateAccessScheduleEvent
            ScheduleExpression: cron(30 14 ? * FRI *)
            ScheduleExpressionTimezone: "Asia/Tokyo"
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: create_access
          TZ: Asia/Tokyo
      Policies:
        - S3FullAccessPolicy:
            BucketName: '{{resolve:ssm:reserva_bucket_info}}'
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMPutGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            - ssm:PutParameters
            - ssm:PutParameter
            Resource: '*'

  ReportFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./reserva_request
      Handler: report.handler
      Runtime: python3.11
      Architectures:
        - arm64
      Layers:
        - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:42
        - !Ref GSpreadLayer
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowHeaders: 
            - "*"
          AllowMethods: 
            - GET
          AllowOrigins: 
            - "*"          
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: create_access
          TZ: Asia/Tokyo
      Policies:
        - S3FullAccessPolicy:
            BucketName: '{{resolve:ssm:reserva_bucket_info}}'
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMPutGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            - ssm:PutParameters
            - ssm:PutParameter
            Resource: '*'

  StoreBatchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./reserva_request
      Handler: storebatch.handler
      Runtime: python3.11
      Architectures:
        - arm64
      Layers:
        - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:42
        - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p311-arm64-pandas:2
        - !Ref GSpreadLayer
      Events:
        ScheduleV2Event:
          Type: ScheduleV2
          Properties:
            Name: StoreBatchScheduleEvent
            ScheduleExpression: cron(0 1 ? * * *)
            ScheduleExpressionTimezone: "Asia/Tokyo"
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: store_batch
          TZ: Asia/Tokyo
      Policies:
        - S3FullAccessPolicy:
            BucketName: '{{resolve:ssm:reserva_bucket_info}}'
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMPutGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            - ssm:PutParameters
            - ssm:PutParameter
            Resource: '*'


  GSpreadLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer description
      ContentUri: 'gspread_layer/'
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

Outputs:
  ReservaRequestUrlEndpoint:
    Description: "ReservaRequest Function URL Endpoint"
    Value:
      Fn::GetAtt: ReservaRequestFunctionUrl.FunctionUrl
  ReportUrlEndpoint:
    Description: "Report Function URL Endpoint"
    Value:
      Fn::GetAtt: ReportFunctionUrl.FunctionUrl